# Generated by Django 2.2.2 on 2020-02-04 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Severe', 'S'), ('Less Severe', 'LS'), ('Casual', 'C')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('reported_time', models.TimeField(auto_now=django.utils.timezone.now)),
                ('date_reported', models.DateField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.Category')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emergency Cases',
                'ordering': ['-reported_time'],
            },
        ),
    ]
